import type { Env } from '../../server/env';
import { audit, getOrCreateCategory } from '../../server/repository';
import { errorResponse, HttpError, json, nowIso, readJson, uuid } from '../../server/http';

function addMonths(date:string,n:number){const d=new Date(`${date}T12:00:00Z`),day=d.getUTCDate();d.setUTCDate(1);d.setUTCMonth(d.getUTCMonth()+n);const last=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0,12)).getUTCDate();d.setUTCDate(Math.min(day,last));return d.toISOString().slice(0,10)}
function inferredFirstDue(purchaseDate:string,closingDay:number,dueDay:number){const d=new Date(`${purchaseDate}T12:00:00Z`),purchaseDay=d.getUTCDate();let monthShift=purchaseDay>closingDay?1:0;const base=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+monthShift,1,12));if(monthShift===0&&dueDay<=closingDay)base.setUTCMonth(base.getUTCMonth()+1);const last=new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,0,12)).getUTCDate();base.setUTCDate(Math.min(dueDay,last));return base.toISOString().slice(0,10)}
async function list(env:Env){const p=await env.DB.prepare(`SELECT cp.*,c.name card_name,cat.name category_name FROM card_purchases cp JOIN cards c ON c.id=cp.card_id LEFT JOIN categories cat ON cat.id=cp.category_id ORDER BY cp.purchase_date DESC,cp.created_at DESC`).all<any>();const ins=await env.DB.prepare('SELECT * FROM card_installments ORDER BY due_date,number').all<any>();return (p.results||[]).map(x=>({id:x.id,cardId:x.card_id,cardName:x.card_name,description:x.description,totalCents:Number(x.total_cents),purchaseDate:x.purchase_date,categoryName:x.category_name,installmentCount:Number(x.installment_count),version:Number(x.version||1),installments:(ins.results||[]).filter(i=>i.purchase_id===x.id).map(i=>({id:i.id,number:Number(i.number),dueDate:i.due_date,amountCents:Number(i.amount_cents),status:i.status}))}));}
export const onRequestGet:PagesFunction<Env>=async({env})=>{try{return json({purchases:await list(env)});}catch(error){return errorResponse(error)}};
export const onRequestPost:PagesFunction<Env>=async({request,env})=>{try{const b=await readJson<any>(request),card=await env.DB.prepare('SELECT * FROM cards WHERE id=? AND archived_at IS NULL').bind(b.cardId).first<any>();if(!card)throw new HttpError(400,'Cartão inválido.');const total=Number(b.totalCents),count=Math.max(1,Number(b.installmentCount||1));if(!Number.isInteger(total)||total<=0||!Number.isInteger(count)||count>60)throw new HttpError(400,'Compra ou parcelas inválidas.');const purchaseDate=b.purchaseDate;if(!/^\d{4}-\d{2}-\d{2}$/.test(purchaseDate||''))throw new HttpError(400,'Data inválida.');const categoryId=await getOrCreateCategory(env,b.categoryName),id=uuid(),now=nowIso(),first=b.firstDueDate||inferredFirstDue(purchaseDate,Number(card.closing_day),Number(card.due_day)),base=Math.floor(total/count),remainder=total-base*count,statements:any[]=[env.DB.prepare('INSERT INTO card_purchases (id,card_id,description,total_cents,purchase_date,category_id,installment_count,created_at,updated_at,version) VALUES (?,?,?,?,?,?,?,?,?,1)').bind(id,b.cardId,(b.description||'Compra').trim(),total,purchaseDate,categoryId,count,now,now)];for(let i=0;i<count;i++){statements.push(env.DB.prepare('INSERT INTO card_installments (id,purchase_id,number,due_date,amount_cents,status,created_at) VALUES (?,?,?,?,?,\'planned\',?)').bind(uuid(),id,i+1,addMonths(first,i),base+(i===count-1?remainder:0),now));}await env.DB.batch(statements);await audit(env,'card_purchase.created','card_purchase',id,null,{id,cardId:b.cardId,totalCents:total,installmentCount:count});return json({purchases:await list(env)},201);}catch(error){return errorResponse(error)}};
