import { useEffect, useMemo, useState } from 'preact/hooks';
import { AdminEntityModal } from '../components/AdminEntityModal';
import { api } from '../data/api';
import { money } from '../lib/money';

type Tab='overview'|'accounts'|'sources'|'categories'|'reserves'|'cards'|'recurring'|'purchases'|'security'|'audit';
type EntityKind='account'|'source'|'category'|'reserve'|'card'|'recurring'|'purchase';

export function Admin(props:{onBack:()=>void}){
  const [tab,setTab]=useState<Tab>('overview');
  const [integrity,setIntegrity]=useState<any>(null),[accounts,setAccounts]=useState<any[]>([]),[sources,setSources]=useState<any[]>([]),[categories,setCategories]=useState<any[]>([]),[reserves,setReserves]=useState<any[]>([]),[cards,setCards]=useState<any[]>([]),[rules,setRules]=useState<any[]>([]),[purchases,setPurchases]=useState<any[]>([]),[sessions,setSessions]=useState<any[]>([]),[audit,setAudit]=useState<any[]>([]);
  const [editor,setEditor]=useState<{kind:EntityKind;item?:any}|null>(null),[error,setError]=useState('');

  async function load(){setError('');try{const [i,a,s,c,r,ca,rr,p,se,au]=await Promise.all([api.integrity(),api.accounts(),api.incomeSources(),api.categories(),api.reserves(),api.cards(),api.recurring(),api.cardPurchases(),api.adminSessions(),api.audit(100)]);setIntegrity(i);setAccounts(a.accounts||[]);setSources(s.sources||[]);setCategories(c.categories||[]);setReserves(r.reserves||[]);setCards(ca.cards||[]);setRules(rr.rules||[]);setPurchases(p.purchases||[]);setSessions(se.sessions||[]);setAudit(au.audit||[]);}catch(e:any){setError(e?.payload?.error||e.message||'Falha ao carregar admin.')}}
  useEffect(()=>{load()},[]);
  const tabs:Record<Tab,string>={overview:'Visão geral',accounts:'Contas',sources:'Fontes',categories:'Categorias',reserves:'Reservas',cards:'Cartões',recurring:'Recorrências',purchases:'Compras',security:'Segurança',audit:'Auditoria'};

  async function remove(kind:EntityKind,item:any){const labels:any={account:'a conta',source:'a fonte',category:'a categoria',reserve:'a reserva',card:'o cartão',recurring:'a recorrência',purchase:'a compra'};if(!confirm(`Excluir/arquivar ${labels[kind]} “${item.name||item.description}”?`))return;try{if(kind==='account')await api.deleteAccount(item.id);else if(kind==='source')await api.deleteIncomeSource(item.id);else if(kind==='category')await api.deleteCategory(item.id);else if(kind==='reserve')await api.deleteReserve(item.id);else if(kind==='card')await api.deleteCard(item.id);else if(kind==='recurring')await api.deleteRecurring(item.id);else await api.deleteCardPurchase(item.id);await load();}catch(e:any){alert(e?.payload?.error||e.message)} }
  function open(kind:EntityKind,item?:any){setEditor({kind,item})}
  async function revoke(id:string){if(!confirm('Encerrar esta sessão?'))return;try{await api.revokeSession(id);await load()}catch(e:any){alert(e?.payload?.error||e.message)}}
  const totalReserved=useMemo(()=>reserves.reduce((s,x)=>s+Number(x.amountCents||0),0),[reserves]);

  return <>
    <div class="adminHeader"><div><div class="kicker">Admin</div><h2>Estrutura, segurança e integridade</h2><p>Manutenção dos dados mestres sem misturar com a operação diária.</p></div><div class="adminHeaderActions"><a class="btn" href={api.backupUrl}>Exportar backup</a><button class="btn" onClick={props.onBack}>Voltar</button></div></div>
    <div class="adminTabs">{(Object.keys(tabs) as Tab[]).map(x=><button class={`tab ${tab===x?'active':''}`} onClick={()=>setTab(x)}>{tabs[x]}</button>)}</div>
    {error&&<div class="error" style="margin-bottom:12px">{error}</div>}
    {tab==='overview'&&<Overview integrity={integrity} accounts={accounts} reserves={reserves} cards={cards} sessions={sessions} totalReserved={totalReserved}/>} 
    {tab==='accounts'&&<ResourceSection title="Contas financeiras" description="Bancos, carteiras, dinheiro e investimentos." onNew={()=>open('account')} rows={accounts.map((x:any)=>({id:x.id,title:x.name,meta:`${money(x.freeCents)} livre · ${money(x.reservedCents)} reservado`,value:money(x.balanceCents),item:x}))} onEdit={(x:any)=>open('account',x)} onDelete={(x:any)=>remove('account',x)}/>} 
    {tab==='sources'&&<ResourceSection title="Fontes de receita" description="Aqui você define exatamente quanto espera receber por mês de cada salário ou fonte." onNew={()=>open('source')} rows={sources.map((x:any)=>({id:x.id,title:x.name,meta:`${x.entryCount} lançamento(s) vinculados`,value:`${money(x.expectedMonthlyCents)} / mês`,item:x}))} onEdit={(x:any)=>open('source',x)} onDelete={(x:any)=>remove('source',x)}/>} 
    {tab==='categories'&&<ResourceSection title="Categorias" description="Categorias e orçamento mensal de referência." onNew={()=>open('category')} rows={categories.map((x:any)=>({id:x.id,title:x.name,meta:`${x.entryCount} lançamento(s)`,value:`meta ${money(x.budgetCents)}`,item:x}))} onEdit={(x:any)=>open('category',x)} onDelete={(x:any)=>remove('category',x)}/>} 
    {tab==='reserves'&&<ResourceSection title="Reservas" description="A mesma reserva pode estar distribuída entre várias contas." onNew={()=>open('reserve')} rows={reserves.map((x:any)=>({id:x.id,title:x.name,meta:(x.allocations||[]).map((a:any)=>`${a.accountName} ${money(a.amountCents)}`).join(' · ')||'Sem alocação',value:`${money(x.amountCents)} / ${money(x.goalCents)}`,item:x}))} onEdit={(x:any)=>open('reserve',x)} onDelete={(x:any)=>remove('reserve',x)}/>} 
    {tab==='cards'&&<ResourceSection title="Cartões" description="Limite, fechamento, vencimento e conta de pagamento." onNew={()=>open('card')} rows={cards.map((x:any)=>({id:x.id,title:x.name,meta:`fecha ${x.closingDay} · vence ${x.dueDay} · ${x.paymentAccountName||'pagamento sem conta fixa'}`,value:`${money(x.committedCents)} / ${money(x.limitCents)}`,item:x}))} onEdit={(x:any)=>open('card',x)} onDelete={(x:any)=>remove('card',x)}/>} 
    {tab==='recurring'&&<ResourceSection title="Recorrências" description="Despesas fixas e receitas recorrentes que alimentam meses futuros." onNew={()=>open('recurring')} rows={rules.map((x:any)=>({id:x.id,title:x.description,meta:`${x.frequency} · ${x.nature==='fixed'?'fixo':'estimado'} · início ${x.startDate}`,value:money(x.amountCents),item:x}))} onEdit={(x:any)=>open('recurring',x)} onDelete={(x:any)=>remove('recurring',x)}/>} 
    {tab==='purchases'&&<ResourceSection title="Compras parceladas" description="Cada parcela gera automaticamente uma obrigação futura no Fluxo." onNew={()=>open('purchase')} rows={purchases.map((x:any)=>({id:x.id,title:x.description,meta:`${x.cardName} · ${x.installmentCount}x · compra ${x.purchaseDate}`,value:money(x.totalCents),item:x}))} onEdit={(x:any)=>open('purchase',x)} onDelete={(x:any)=>remove('purchase',x)}/>} 
    {tab==='security'&&<Security sessions={sessions} integrity={integrity} onRevoke={revoke}/>} 
    {tab==='audit'&&<Audit rows={audit}/>} 
    {editor&&<AdminEntityModal kind={editor.kind} item={editor.item} accounts={accounts} cards={cards} onClose={()=>setEditor(null)} onSaved={async()=>{setEditor(null);await load()}}/>}
  </>;
}

function Overview({integrity,accounts,reserves,cards,sessions,totalReserved}:any){return <><div class="adminMetricGrid"><div class="miniCard"><small>Contas financeiras</small><strong>{accounts.length}</strong></div><div class="miniCard"><small>Reservado</small><strong>{money(totalReserved)}</strong></div><div class="miniCard"><small>Cartões ativos</small><strong>{cards.length}</strong></div><div class="miniCard"><small>Sessões ativas</small><strong>{sessions.length}</strong></div></div><div class="adminGrid" style="margin-top:14px"><section class="panel adminPanel"><div class="kicker">Integridade</div>{integrity?.checks?Object.entries(integrity.checks).map(([key,value])=><div class="adminLine"><span>{humanCheck(key)}</span><strong class={value?'income':'expense'}>{value?'OK':'ERRO'}</strong></div>):<div class="muted">Verificando…</div>}</section><section class="panel adminPanel"><div class="kicker">Segurança</div><div class="adminLine"><span>Sessões</span><strong>{integrity?.sessions??'—'}</strong></div><div class="adminLine"><span>Origens temporariamente bloqueadas</span><strong>{integrity?.lockedAttempts??'—'}</strong></div><p class="muted">A API inteira exige sessão. Após falhas repetidas o login exige Turnstile e aplica bloqueio temporário por origem.</p></section></div></>}
function ResourceSection({title,description,onNew,rows,onEdit,onDelete}:any){return <><div class="sectionTitle"><div><h2>{title}</h2><p>{description}</p></div><button class="btn primary" onClick={onNew}>Novo</button></div><div class="adminResourceList">{rows.length?rows.map((r:any)=><div class="adminResourceRow" key={r.id}><div><strong>{r.title}</strong><small>{r.meta}</small></div><div class="adminResourceValue">{r.value}</div><div class="adminResourceActions"><button class="btn" onClick={()=>onEdit(r.item)}>Editar</button><button class="btn danger" onClick={()=>onDelete(r.item)}>Excluir</button></div></div>):<div class="empty">Nenhum item cadastrado.</div>}</div></>}
function Security({sessions,integrity,onRevoke}:any){return <><div class="sectionTitle"><div><h2>Sessões</h2><p>Revogue acessos antigos sem afetar a sessão atual.</p></div></div><div class="adminResourceList">{sessions.map((s:any)=><div class="adminResourceRow" key={s.id}><div><strong>{s.current?'Este dispositivo / sessão atual':'Sessão autenticada'}</strong><small>último uso {fmt(s.lastSeenAt)} · expira {fmt(s.expiresAt)}</small></div><div class="adminResourceValue">{s.current?'ATUAL':''}</div><div class="adminResourceActions">{!s.current&&<button class="btn danger" onClick={()=>onRevoke(s.id)}>Encerrar</button>}</div></div>)}</div><div class="sectionTitle"><div><h2>Rate limit</h2></div></div><div class="panel adminPanel"><div class="adminLine"><span>Bloqueios ativos</span><strong>{integrity?.lockedAttempts??0}</strong></div><p class="muted">5 falhas na janela acionam bloqueio temporário; após falhas repetidas o Turnstile é exigido quando configurado.</p></div></>}
function Audit({rows}:any){return <><div class="sectionTitle"><div><h2>Auditoria</h2><p>Últimas alterações estruturais e financeiras registradas pelo servidor.</p></div></div><div class="adminResourceList">{rows.length?rows.map((x:any)=><div class="adminResourceRow" key={x.id}><div><strong>{x.action}</strong><small>{x.entityType} · {x.entityId||'—'} · {fmt(x.createdAt)}</small></div><div class="adminResourceValue"></div><div class="adminResourceActions"></div></div>):<div class="empty">Nenhum evento registrado.</div>}</div></>}
function humanCheck(k:string){return ({foreignKeys:'Foreign keys',settlements:'Baixas ≤ lançamentos',recurrences:'Recorrências sem duplicidade',reserves:'Reservas compatíveis com contas'} as any)[k]||k}
function fmt(v:string){try{return new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v))}catch{return v}}
