import { useMemo, useState } from 'preact/hooks';
import { api } from '../data/api';
import { toCents } from '../lib/money';

type Kind='account'|'category'|'source'|'reserve'|'card'|'recurring'|'purchase';

export function AdminEntityModal(props:{kind:Kind;item?:any;accounts:any[];cards:any[];onClose:()=>void;onSaved:()=>void}){
  const item=props.item||{};
  const [form,setForm]=useState<Record<string,any>>(()=>initialForm(props.kind,item,props.accounts));
  const [saving,setSaving]=useState(false),[error,setError]=useState('');
  const title=useMemo(()=>({account:'conta financeira',category:'categoria',source:'fonte de receita',reserve:'reserva',card:'cartão',recurring:'recorrência',purchase:'compra no cartão'}[props.kind]),[props.kind]);
  const set=(k:string,v:any)=>setForm(x=>({...x,[k]:v}));

  async function submit(e:Event){e.preventDefault();setSaving(true);setError('');try{
    if(props.kind==='account'){
      const body:any={name:form.name,type:form.type};
      if(item.id)body.targetBalanceCents=toCents(form.balance);else body.openingBalanceCents=toCents(form.balance);
      item.id?await api.patchAccount(item.id,body):await api.createAccount(body);
    }else if(props.kind==='category'){
      const body={name:form.name,budgetCents:toCents(form.budget)};item.id?await api.patchCategory(item.id,body):await api.createCategory(body);
    }else if(props.kind==='source'){
      const body={name:form.name,expectedMonthlyCents:toCents(form.expected)};item.id?await api.patchIncomeSource(item.id,body):await api.createIncomeSource(body);
    }else if(props.kind==='reserve'){
      const allocations=props.accounts.map(a=>({accountId:a.id,amountCents:toCents(form[`allocation_${a.id}`]||0)})).filter(a=>a.amountCents>0);
      if(item.id)await api.patchReserve(item.id,{name:form.name,goalCents:toCents(form.goal),allocations});
      else{const first=allocations[0];await api.createReserve({name:form.name,goalCents:toCents(form.goal),amountCents:first?.amountCents||0,accountId:first?.accountId||null});if(allocations.length>1){const list=await api.reserves();const created=(list.reserves||[]).find((r:any)=>r.name===form.name);if(created)await api.patchReserve(created.id,{allocations});}}
    }else if(props.kind==='card'){
      const body={name:form.name,limitCents:toCents(form.limit),closingDay:Number(form.closingDay),dueDay:Number(form.dueDay),paymentAccountId:form.paymentAccountId||null};item.id?await api.patchCard(item.id,body):await api.createCard(body);
    }else if(props.kind==='recurring'){
      const body:any={kind:form.entryKind,description:form.description,amountCents:toCents(form.amount),frequency:form.frequency,nature:form.nature,startDate:form.startDate,endDate:form.endDate||null,accountId:form.accountId||null,paymentMethod:form.paymentMethod};if(form.entryKind==='income')body.incomeSourceName=form.label;else body.categoryName=form.label;item.id?await api.patchRecurring(item.id,body):await api.createRecurring(body);
    }else{
      const body={cardId:form.cardId,description:form.description,totalCents:toCents(form.total),purchaseDate:form.purchaseDate,categoryName:form.categoryName,installmentCount:Number(form.installmentCount||1),firstDueDate:form.firstDueDate||undefined};item.id?await api.patchCardPurchase(item.id,body):await api.createCardPurchase(body);
    }
    props.onSaved();
  }catch(err:any){setError(err?.payload?.error||err?.message||'Não foi possível salvar.')}finally{setSaving(false)}}

  return <div class="modalBackdrop" onClick={e=>e.currentTarget===e.target&&props.onClose()}><form class="modal adminModal" onSubmit={submit}><div class="modalTitle"><div><div class="kicker">Admin</div><h2>{item.id?'Editar':'Nova'} {title}</h2></div><button type="button" class="btn" onClick={props.onClose}>Fechar</button></div><div class="formGrid">{fields()}</div>{error&&<div class="error">{error}</div>}<div class="modalActions"><button type="button" class="btn" onClick={props.onClose}>Cancelar</button><button class="btn primary" disabled={saving}>{saving?'Salvando…':'Salvar alterações'}</button></div></form></div>;

  function fields(){
    if(props.kind==='account')return <><Field label="Nome"><input class="input" required value={form.name} onInput={e=>set('name',(e.target as HTMLInputElement).value)}/></Field><Field label="Tipo"><select class="select" value={form.type} onChange={e=>set('type',(e.target as HTMLSelectElement).value)}><option value="bank">Banco</option><option value="wallet">Carteira digital</option><option value="cash">Dinheiro</option><option value="investment">Investimento</option></select></Field><Field label={item.id?'Saldo atual / corrigido':'Saldo inicial'} full><input class="input" inputMode="decimal" value={form.balance} onInput={e=>set('balance',(e.target as HTMLInputElement).value)}/></Field></>;
    if(props.kind==='category')return <><Field label="Nome" full><input class="input" required value={form.name} onInput={e=>set('name',(e.target as HTMLInputElement).value)}/></Field><Field label="Orçamento mensal" full><input class="input" inputMode="decimal" value={form.budget} onInput={e=>set('budget',(e.target as HTMLInputElement).value)}/></Field></>;
    if(props.kind==='source')return <><Field label="Nome da fonte" full><input class="input" required value={form.name} onInput={e=>set('name',(e.target as HTMLInputElement).value)}/></Field><Field label="Valor esperado por mês" full><input class="input" inputMode="decimal" value={form.expected} onInput={e=>set('expected',(e.target as HTMLInputElement).value)}/></Field></>;
    if(props.kind==='reserve')return <><Field label="Nome"><input class="input" required value={form.name} onInput={e=>set('name',(e.target as HTMLInputElement).value)}/></Field><Field label="Meta"><input class="input" inputMode="decimal" value={form.goal} onInput={e=>set('goal',(e.target as HTMLInputElement).value)}/></Field><div class="field full"><label>Onde o dinheiro está</label><div class="allocationEditor">{props.accounts.map(a=><label class="allocationLine"><span>{a.name}</span><input class="input" inputMode="decimal" value={form[`allocation_${a.id}`]||''} placeholder="0,00" onInput={e=>set(`allocation_${a.id}`,(e.target as HTMLInputElement).value)}/></label>)}</div></div></>;
    if(props.kind==='card')return <><Field label="Nome"><input class="input" required value={form.name} onInput={e=>set('name',(e.target as HTMLInputElement).value)}/></Field><Field label="Limite"><input class="input" inputMode="decimal" value={form.limit} onInput={e=>set('limit',(e.target as HTMLInputElement).value)}/></Field><Field label="Fecha dia"><input class="input" type="number" min="1" max="31" value={form.closingDay} onInput={e=>set('closingDay',(e.target as HTMLInputElement).value)}/></Field><Field label="Vence dia"><input class="input" type="number" min="1" max="31" value={form.dueDay} onInput={e=>set('dueDay',(e.target as HTMLInputElement).value)}/></Field><Field label="Conta que paga a fatura" full><select class="select" value={form.paymentAccountId} onChange={e=>set('paymentAccountId',(e.target as HTMLSelectElement).value)}><option value="">Definir no pagamento</option>{props.accounts.map(a=><option value={a.id}>{a.name}</option>)}</select></Field></>;
    if(props.kind==='recurring')return <><Field label="Tipo"><select class="select" value={form.entryKind} onChange={e=>set('entryKind',(e.target as HTMLSelectElement).value)}><option value="expense">Despesa</option><option value="income">Receita</option></select></Field><Field label="Descrição"><input class="input" required value={form.description} onInput={e=>set('description',(e.target as HTMLInputElement).value)}/></Field><Field label="Valor"><input class="input" inputMode="decimal" value={form.amount} onInput={e=>set('amount',(e.target as HTMLInputElement).value)}/></Field><Field label={form.entryKind==='income'?'Fonte':'Categoria'}><input class="input" value={form.label} onInput={e=>set('label',(e.target as HTMLInputElement).value)}/></Field><Field label="Frequência"><select class="select" value={form.frequency} onChange={e=>set('frequency',(e.target as HTMLSelectElement).value)}><option value="weekly">Semanal</option><option value="biweekly">Quinzenal</option><option value="monthly">Mensal</option><option value="yearly">Anual</option></select></Field><Field label="Valor"><select class="select" value={form.nature} onChange={e=>set('nature',(e.target as HTMLSelectElement).value)}><option value="fixed">Fixo</option><option value="estimated">Estimado / variável</option></select></Field><Field label="Início"><input class="input" type="date" value={form.startDate} onInput={e=>set('startDate',(e.target as HTMLInputElement).value)}/></Field><Field label="Fim"><input class="input" type="date" value={form.endDate} onInput={e=>set('endDate',(e.target as HTMLInputElement).value)}/></Field><Field label="Conta"><select class="select" value={form.accountId} onChange={e=>set('accountId',(e.target as HTMLSelectElement).value)}><option value="">Sem conta definida</option>{props.accounts.map(a=><option value={a.id}>{a.name}</option>)}</select></Field><Field label="Pagamento"><select class="select" value={form.paymentMethod} onChange={e=>set('paymentMethod',(e.target as HTMLSelectElement).value)}><option>Pix</option><option>Débito</option><option>Crédito</option><option>Dinheiro</option><option>Transferência</option></select></Field></>;
    return <><Field label="Cartão"><select class="select" required value={form.cardId} onChange={e=>set('cardId',(e.target as HTMLSelectElement).value)}><option value="">Selecione</option>{props.cards.map(c=><option value={c.id}>{c.name}</option>)}</select></Field><Field label="Descrição"><input class="input" required value={form.description} onInput={e=>set('description',(e.target as HTMLInputElement).value)}/></Field><Field label="Valor total"><input class="input" inputMode="decimal" value={form.total} onInput={e=>set('total',(e.target as HTMLInputElement).value)}/></Field><Field label="Categoria"><input class="input" value={form.categoryName} onInput={e=>set('categoryName',(e.target as HTMLInputElement).value)}/></Field><Field label="Data da compra"><input class="input" type="date" value={form.purchaseDate} onInput={e=>set('purchaseDate',(e.target as HTMLInputElement).value)}/></Field><Field label="Parcelas"><input class="input" type="number" min="1" max="60" value={form.installmentCount} onInput={e=>set('installmentCount',(e.target as HTMLInputElement).value)}/></Field><Field label="Primeiro vencimento" full><input class="input" type="date" value={form.firstDueDate} onInput={e=>set('firstDueDate',(e.target as HTMLInputElement).value)}/></Field></>;
  }
}

function Field(props:{label:string;full?:boolean;children:any}){return <div class={`field ${props.full?'full':''}`}><label>{props.label}</label>{props.children}</div>}
function initialForm(kind:Kind,item:any,accounts:any[]){const today=new Date().toISOString().slice(0,10);if(kind==='account')return{name:item.name||'',type:item.type||'bank',balance:String((item.balanceCents||0)/100)};if(kind==='category')return{name:item.name||'',budget:String((item.budgetCents||0)/100)};if(kind==='source')return{name:item.name||'',expected:String((item.expectedMonthlyCents||0)/100)};if(kind==='reserve'){const f:any={name:item.name||'',goal:String((item.goalCents||0)/100)};for(const a of accounts){const al=(item.allocations||[]).find((x:any)=>x.accountId===a.id);f[`allocation_${a.id}`]=al?String(al.amountCents/100):''}return f}if(kind==='card')return{name:item.name||'',limit:String((item.limitCents||0)/100),closingDay:item.closingDay||5,dueDay:item.dueDay||12,paymentAccountId:item.paymentAccountId||''};if(kind==='recurring')return{entryKind:item.kind||'expense',description:item.description||'',amount:String((item.amountCents||0)/100),label:item.categoryName||item.incomeSourceName||'',frequency:item.frequency||'monthly',nature:item.nature||'fixed',startDate:item.startDate||today,endDate:item.endDate||'',accountId:item.accountId||'',paymentMethod:item.paymentMethod||'Pix'};return{cardId:item.cardId||'',description:item.description||'',total:String((item.totalCents||0)/100),categoryName:item.categoryName||'',purchaseDate:item.purchaseDate||today,installmentCount:item.installmentCount||1,firstDueDate:item.installments?.[0]?.dueDate||''}}
